# Generated by Django 5.1 on 2024-09-28 00:35

import asodi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('nombre_convenio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('horas_llamado', models.IntegerField(validators=[asodi.models.validate_positive])),
                ('dias_para_operar', models.IntegerField(validators=[asodi.models.validate_positive])),
                ('dias_para_alertar', models.IntegerField(validators=[asodi.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[asodi.models.validate_rut])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAsodiAd',
            fields=[
                ('rut_ad', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[asodi.models.validate_rut])),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('estado_ad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAsodiAdmin',
            fields=[
                ('correo', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FichaPersonal',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asodi.usuario')),
                ('edad', models.IntegerField(validators=[asodi.models.validate_positive])),
                ('estatura', models.FloatField(validators=[asodi.models.validate_positive])),
                ('sexo', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('hospital_perteneciente', models.CharField(max_length=20)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('enfermedad_corazon', models.BooleanField(default=False)),
                ('accidente_vascular', models.BooleanField(default=False)),
                ('trombosis', models.BooleanField(default=False)),
                ('epilepsia', models.BooleanField(default=False)),
                ('alergias', models.BooleanField(default=False)),
                ('numero_contacto', models.IntegerField(validators=[asodi.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCitasMedicas',
            fields=[
                ('id_cita_medica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre_medico', models.CharField(max_length=25)),
                ('motivo_consulta', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id_peso', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.IntegerField(validators=[asodi.models.validate_positive])),
                ('fecha_registro', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPresion',
            fields=[
                ('id_presion', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('presion_diastolica', models.IntegerField(validators=[asodi.models.validate_positive])),
                ('presion_sistolica', models.IntegerField(validators=[asodi.models.validate_positive])),
                ('frecuenciacardiaca', models.IntegerField(validators=[asodi.models.validate_positive])),
                ('fecha_registro', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSintoma',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sintoma', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanillasConvenio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField()),
                ('rut', models.CharField(max_length=9, validators=[asodi.models.validate_rut])),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('apellido_paciente', models.CharField(max_length=50)),
                ('fecha_sic', models.DateField(blank=True, null=True)),
                ('reg_primer_llamado', models.DateField()),
                ('reg_segundo_llamado', models.DateField(blank=True, null=True)),
                ('reg_tercer_llamado', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('doctor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('fecha_cirugia', models.DateField(blank=True, null=True)),
                ('control_post_operatorio', models.DateField(blank=True, null=True)),
                ('control_mes', models.DateField(blank=True, null=True)),
                ('estado_paciente', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En proceso'), ('A', 'Alta')], default='P', max_length=1)),
                ('convenios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.convenios')),
                ('usuario_asodi_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuarioasodiad')),
            ],
        ),
        migrations.AddField(
            model_name='convenios',
            name='usuario_asodi_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuarioasodiadmin'),
        ),
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado_an', models.BooleanField(default=True)),
                ('usuario_asodi_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuarioasodiadmin')),
            ],
        ),
    ]
