# Generated by Django 5.1 on 2024-08-27 02:45

import asodi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id_medicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('tipo_medicamento', models.CharField(max_length=15)),
                ('frecuencia_hora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[asodi.models.validate_rut])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAsodi',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo_electronico', models.EmailField(max_length=35)),
                ('contraseña', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMediTomado',
            fields=[
                ('id_registro_medi', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_toma', models.DateField()),
                ('confirmacion_toma', models.BooleanField()),
                ('medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.medicacion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSintoma',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sintoma', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPresion',
            fields=[
                ('id_presion', models.AutoField(primary_key=True, serialize=False)),
                ('presion_diastolica', models.FloatField()),
                ('presion_sistolica', models.FloatField()),
                ('fecha_registro', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id_peso', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('fecha_registro', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCitasMedicas',
            fields=[
                ('id_cita_medica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre_medico', models.CharField(max_length=25)),
                ('motivo_consulta', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='medicacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario'),
        ),
        migrations.CreateModel(
            name='FichaPersonal',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('sexo', models.BooleanField()),
                ('hospital_perteneciente', models.CharField(max_length=20)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('enfermedad_corazon', models.BooleanField(default=False)),
                ('accidente_vascular', models.BooleanField(default=False)),
                ('trombosis', models.BooleanField(default=False)),
                ('epilepsia', models.BooleanField(default=False)),
                ('alergias', models.BooleanField(default=False)),
                ('numero_contacto', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('titulo', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('usuario_asodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuarioasodi')),
            ],
        ),
    ]
