# Generated by Django 5.1 on 2024-08-27 04:28

import asodi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapersonal',
            name='edad',
            field=models.IntegerField(validators=[asodi.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='fichapersonal',
            name='estatura',
            field=models.FloatField(validators=[asodi.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='fichapersonal',
            name='numero_contacto',
            field=models.IntegerField(validators=[asodi.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='cantidad',
            field=models.IntegerField(validators=[asodi.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='frecuencia_hora',
            field=models.IntegerField(validators=[asodi.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='registropeso',
            name='peso',
            field=models.FloatField(validators=[asodi.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='registropresion',
            name='presion_diastolica',
            field=models.FloatField(validators=[asodi.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='registropresion',
            name='presion_sistolica',
            field=models.FloatField(validators=[asodi.models.validate_positive]),
        ),
    ]
