# Generated by Django 5.1 on 2024-09-28 02:20

import asodi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioasodiad',
            name='rut_ad',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[asodi.models.validate_rut]),
        ),
    ]
