# Generated by Django 5.1 on 2024-09-28 05:26

import asodi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0002_alter_usuarioasodiad_rut_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillasconvenio',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[asodi.models.validate_rut]),
        ),
    ]
