# Generated by Django 5.1 on 2024-08-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0002_alter_fichapersonal_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapersonal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1),
        ),
    ]
