# Generated by Django 5.1 on 2024-09-28 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0003_alter_planillasconvenio_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_soli', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=1)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('planilla_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.planillasconvenio')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.usuarioasodiad')),
            ],
        ),
    ]
