# Generated by Django 5.1 on 2024-08-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0003_alter_fichapersonal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
