# Generated by Django 5.1 on 2024-09-02 06:53

import asodi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0004_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[asodi.models.validate_rut]),
        ),
        migrations.AlterField(
            model_name='usuarioasodi',
            name='correo_electronico',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
