# Generated by Django 5.1 on 2024-09-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0004_solicitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/'),
        ),
    ]
