# Generated by Django 5.1 on 2024-09-05 02:50

import asodi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0005_alter_usuario_correo_alter_usuario_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropresion',
            name='frecuenciacardiaca',
            field=models.IntegerField(default=120, validators=[asodi.models.validate_positive]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registropresion',
            name='presion_diastolica',
            field=models.IntegerField(validators=[asodi.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='registropresion',
            name='presion_sistolica',
            field=models.IntegerField(validators=[asodi.models.validate_positive]),
        ),
    ]
