# Generated by Django 5.1 on 2024-10-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0005_anuncios_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planillasconvenio',
            old_name='id',
            new_name='id_planilla',
        ),
    ]
