# Generated by Django 5.1 on 2024-09-05 03:15

import asodi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0006_registropresion_frecuenciacardiaca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropeso',
            name='peso',
            field=models.IntegerField(validators=[asodi.models.validate_positive]),
        ),
    ]
