# Generated by Django 5.1 on 2024-10-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0006_rename_id_planillasconvenio_id_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillasconvenio',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planillasconvenio',
            name='estado_paciente',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En proceso'), ('O', 'Operado'), ('A', 'Alta'), ('R', 'Rechazado')], default='P', max_length=1),
        ),
    ]
