# Generated by Django 5.1 on 2024-10-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0007_planillasconvenio_motivo_rechazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillasconvenio',
            name='fecha_recepcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
