# Generated by Django 5.1 on 2024-09-05 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0007_alter_registropeso_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichapersonal',
            name='id_ficha',
        ),
        migrations.AlterField(
            model_name='fichapersonal',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asodi.usuario'),
        ),
    ]
