# Generated by Django 5.1 on 2024-09-06 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0008_remove_fichapersonal_id_ficha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_generico', models.CharField(help_text='Nombre genérico del medicamento', max_length=100)),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial del medicamento', max_length=100)),
                ('composicion', models.TextField(help_text='Composición detallada del medicamento')),
                ('forma_farmaceutica', models.CharField(choices=[('tableta', 'Tableta'), ('capsula', 'Cápsula'), ('jarabe', 'Jarabe'), ('inyeccion', 'Inyección'), ('crema', 'Crema')], help_text='Forma farmacéutica del medicamento', max_length=50)),
                ('indicaciones', models.TextField(help_text='Indicaciones para el uso del medicamento')),
                ('dosis', models.CharField(help_text='Dosis recomendada', max_length=100)),
                ('contraindicaciones', models.TextField(blank=True, help_text='Contraindicaciones del medicamento')),
                ('advertencias', models.TextField(blank=True, help_text='Advertencias y precauciones')),
                ('interacciones', models.TextField(blank=True, help_text='Interacciones con otros medicamentos o alimentos')),
                ('efectos_secundarios', models.TextField(blank=True, help_text='Efectos secundarios posibles')),
                ('sobredosis', models.TextField(blank=True, help_text='Tratamiento y síntomas de sobredosis')),
                ('condiciones_almacenamiento', models.CharField(help_text='Condiciones de almacenamiento', max_length=100)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.RemoveField(
            model_name='registromeditomado',
            name='id_registro_medi',
        ),
        migrations.AddField(
            model_name='registromeditomado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asodi.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registromeditomado',
            name='medicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asodi.medicamento'),
        ),
        migrations.DeleteModel(
            name='Medicacion',
        ),
    ]
