# Generated by Django 5.1 on 2024-10-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0008_alter_planillasconvenio_fecha_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
