# Generated by Django 5.1 on 2024-10-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0009_alter_anuncios_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropresion',
            name='id_presion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
