# Generated by Django 5.1 on 2024-09-06 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0009_medicamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromeditomado',
            name='id_res_medicamento',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registromeditomado',
            name='medicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asodi.medicamento'),
        ),
    ]
