# Generated by Django 5.1 on 2024-10-20 03:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0010_alter_registropresion_id_presion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillasconvenio',
            name='fecha_recepcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
