# Generated by Django 5.1 on 2024-09-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0010_registromeditomado_id_res_medicamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registromeditomado',
            old_name='id_res_medicamento',
            new_name='id_medicamento_regist',
        ),
        migrations.AlterField(
            model_name='registropresion',
            name='id_presion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
