# Generated by Django 5.1 on 2024-09-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0010_registromeditomado_id_res_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropresion',
            name='id_presion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
