# Generated by Django 5.1 on 2024-09-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0011_rename_id_res_medicamento_registromeditomado_id_medicamento_regist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromeditomado',
            name='id_res_medicamento',
        ),
        migrations.AlterField(
            model_name='registropresion',
            name='id_presion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
