# Generated by Django 5.1 on 2024-09-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0011_alter_registropresion_id_presion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registromeditomado',
            old_name='id_res_medicamento',
            new_name='id_resgis_medicamento',
        ),
    ]
