# Generated by Django 5.1 on 2024-09-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0011_rename_id_res_medicamento_registromeditomado_id_medicamento_regist_and_more'),
    ]

    operations = [
    ]
