# Generated by Django 5.1 on 2024-09-24 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0012_rename_id_medicamento_regist_registromeditomado_id_medic_regist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromeditomado',
            name='medicacion',
        ),
        migrations.RemoveField(
            model_name='registromeditomado',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='RegistroMediTomado',
        ),
    ]
