# Generated by Django 5.1 on 2024-09-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asodi', '0013_alter_registromeditomado_id_medic_regist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromeditomado',
            name='id_medic_regist',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
